server:
  port: 9011
spring:
  application:
    name: my-manager
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    my-base:
      path: /base/**
      serviceId: my-base
  sensitive-headers:
jwt:
  config:
    signKey: joey
    expireDuring: 0