server:
  port: 12000
spring:
  application:
    name: my-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/joeylwq/myProject01.git
  rabbitmq:
    host: 127.0.0.1
management:
  endpoint:
    web:
      exposure:
        include: bus-refresh