server:
  port: 9002
  tomcat:
    max-http-header-size: 8192
spring:
  application:
    name: my-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/myProject1?serverTimezone=UTC
    username: root
    password: password
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
  redis:
    host: 127.0.0.1
  rabbitmq:
    host: 127.0.0.1
jwt:
  config:
    signKey: joey
    expireDuring: 0
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true